implement floor division
videlec/e-antic pull request #142
Opened 2020-11-14 19:30 UTC by saraedum

fixes #139

2020-11-14 20:11 UTC, saraedum commented
@videlec any objections to merging this? I'd like to cut a new rc release after that.

2020-11-15 07:54 UTC, videlec commented
We could completely avoid the `renf_elem` division `b / c` here. Namely
- refine `quotient = arb(b) / arb(c)` until its diameter is < 0.5
- if `quotient` does not contain an integer: easy
- if `quotient` contains the integer `n` then if `n*c <= b` return `n` otherwise return `n-1`
Above you only perform an integer multiplication which is way cheaper in arithmetic than the plain division.

2020-11-15 18:22 UTC, saraedum commented
@videlec that's much smarter of course. It's implemented like that now. The tests took 6s before, now they take 4s.

2020-11-15 18:32 UTC, videlec requested changes

2020-11-15 18:32 UTC, videlec commented on renf_elem/fdiv.c
> +        renf_elem_set_evaluation(c, nf, prec + bcond);
Shouldn't it be ccond here?

2020-11-15 18:32 UTC, videlec commented on renf_elem/fdiv.c
> +
Shouldn't we ensure that c->emb does not contain zero?

2020-11-15 18:37 UTC, saraedum commented on renf_elem/fdiv.c
> +        renf_elem_set_evaluation(c, nf, prec + bcond);
oops

2020-11-15 18:37 UTC, saraedum commented on renf_elem/fdiv.c
> +
more oops

2020-11-15 18:40 UTC, saraedum commented on renf_elem/fdiv.c
> +
If the precision has changed for c, I could now call `renf_elem_set_evaluation` for `b` again. But it's not clear that it's always a good idea.

2020-11-15 18:42 UTC, videlec commented on renf_elem/fdiv.c
> +
I don't see how tests could catch such thing. The `ccond` is just a number to ensure that you end up with an embedding with at least `prec` valid bits. Did you have something in mind?

2020-11-15 18:46 UTC, videlec commented on renf_elem/fdiv.c
> +
I think it is fine the way you wrote it. In many situations the default embeddings are already good enough to determine the fdiv.

2020-11-15 18:51 UTC, saraedum commented on renf_elem/fdiv.c
> +
No, I mean, why the tests did not catch the `c` contains zero case. Apparently, the random renf_elems do not contain numbers very close to zero.

2020-11-15 18:57 UTC, videlec commented on renf_elem/fdiv.c
> +
Oh, true. This is annoying. However creating a small nonzero number field element is not trivial. If you pick coefficients at random you will never find a small one. Maybe we should tweak the random generator to make them often enough. see #143

2020-11-15 20:19 UTC, videlec approved these changes

2020-11-15 20:19 UTC, merged